// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerServer.Context;

#nullable disable

namespace SneakerServer.Migrations
{
    [DbContext(typeof(SneakerContext))]
    [Migration("20250109121244_UpdatedUser")]
    partial class UpdatedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SneakerServer.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "361 Degrees"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "A.S.O"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "Abaeté (clothing)"
                        },
                        new
                        {
                            BrandId = 4,
                            Name = "ABC-Mart"
                        },
                        new
                        {
                            BrandId = 5,
                            Name = "Adidas"
                        },
                        new
                        {
                            BrandId = 6,
                            Name = "Airness"
                        },
                        new
                        {
                            BrandId = 7,
                            Name = "Alden Shoe Company"
                        },
                        new
                        {
                            BrandId = 8,
                            Name = "Allen Edmonds"
                        },
                        new
                        {
                            BrandId = 9,
                            Name = "Alpinestars"
                        },
                        new
                        {
                            BrandId = 10,
                            Name = "Ari Football"
                        },
                        new
                        {
                            BrandId = 11,
                            Name = "Ariat"
                        },
                        new
                        {
                            BrandId = 12,
                            Name = "Asics"
                        },
                        new
                        {
                            BrandId = 13,
                            Name = "Atoms (shoes)"
                        },
                        new
                        {
                            BrandId = 14,
                            Name = "Aubercy"
                        },
                        new
                        {
                            BrandId = 15,
                            Name = "Avia (shoes)"
                        },
                        new
                        {
                            BrandId = 16,
                            Name = "Baldinini"
                        },
                        new
                        {
                            BrandId = 17,
                            Name = "Bally (fashion house)"
                        },
                        new
                        {
                            BrandId = 18,
                            Name = "Banana Republic"
                        },
                        new
                        {
                            BrandId = 19,
                            Name = "Bata Corporation"
                        },
                        new
                        {
                            BrandId = 20,
                            Name = "Bearpaw (brand)"
                        },
                        new
                        {
                            BrandId = 21,
                            Name = "Belle International"
                        },
                        new
                        {
                            BrandId = 22,
                            Name = "Stefano Bemer"
                        },
                        new
                        {
                            BrandId = 23,
                            Name = "Bettanin & Venturi"
                        },
                        new
                        {
                            BrandId = 24,
                            Name = "Birkenstock"
                        },
                        new
                        {
                            BrandId = 25,
                            Name = "Blackstock & Weber"
                        },
                        new
                        {
                            BrandId = 26,
                            Name = "Bontoni"
                        },
                        new
                        {
                            BrandId = 27,
                            Name = "Bucketfeet"
                        },
                        new
                        {
                            BrandId = 28,
                            Name = "Caleres"
                        },
                        new
                        {
                            BrandId = 29,
                            Name = "Calvin Klein (fashion house)"
                        },
                        new
                        {
                            BrandId = 30,
                            Name = "Calzaturificio fratelli soldini"
                        },
                        new
                        {
                            BrandId = 31,
                            Name = "Camper (company)"
                        },
                        new
                        {
                            BrandId = 32,
                            Name = "Cariuma"
                        },
                        new
                        {
                            BrandId = 33,
                            Name = "Caterpillar Inc."
                        },
                        new
                        {
                            BrandId = 34,
                            Name = "Chaco (footwear)"
                        },
                        new
                        {
                            BrandId = 35,
                            Name = "Charles David (company)"
                        },
                        new
                        {
                            BrandId = 36,
                            Name = "Church's"
                        },
                        new
                        {
                            BrandId = 37,
                            Name = "Circa (company)"
                        },
                        new
                        {
                            BrandId = 38,
                            Name = "Colchester Rubber Co."
                        },
                        new
                        {
                            BrandId = 39,
                            Name = "Cole Haan"
                        },
                        new
                        {
                            BrandId = 40,
                            Name = "Columbia Montrail"
                        },
                        new
                        {
                            BrandId = 41,
                            Name = "Columbia Sportswear"
                        },
                        new
                        {
                            BrandId = 42,
                            Name = "Common Projects"
                        },
                        new
                        {
                            BrandId = 43,
                            Name = "Crocs"
                        },
                        new
                        {
                            BrandId = 44,
                            Name = "DC Shoes"
                        },
                        new
                        {
                            BrandId = 45,
                            Name = "Mohamed Dia"
                        },
                        new
                        {
                            BrandId = 46,
                            Name = "Diadora"
                        },
                        new
                        {
                            BrandId = 47,
                            Name = "Dr. Kong (brand)"
                        },
                        new
                        {
                            BrandId = 48,
                            Name = "Dr. Martens"
                        },
                        new
                        {
                            BrandId = 49,
                            Name = "Duarig"
                        },
                        new
                        {
                            BrandId = 50,
                            Name = "Dune London"
                        },
                        new
                        {
                            BrandId = 51,
                            Name = "Dunlop Sport (Australia)"
                        },
                        new
                        {
                            BrandId = 52,
                            Name = "DVS Shoes"
                        },
                        new
                        {
                            BrandId = 53,
                            Name = "EbLens"
                        },
                        new
                        {
                            BrandId = 54,
                            Name = "ECCO"
                        },
                        new
                        {
                            BrandId = 55,
                            Name = "Ed Meier"
                        },
                        new
                        {
                            BrandId = 56,
                            Name = "Edward Green & Co."
                        },
                        new
                        {
                            BrandId = 57,
                            Name = "EMU Australia"
                        },
                        new
                        {
                            BrandId = 58,
                            Name = "Erreà"
                        },
                        new
                        {
                            BrandId = 59,
                            Name = "Etnies"
                        },
                        new
                        {
                            BrandId = 60,
                            Name = "Falc"
                        },
                        new
                        {
                            BrandId = 61,
                            Name = "Fallen Footwear"
                        },
                        new
                        {
                            BrandId = 62,
                            Name = "Famolare"
                        },
                        new
                        {
                            BrandId = 63,
                            Name = "FBT (company)"
                        },
                        new
                        {
                            BrandId = 64,
                            Name = "FEIT"
                        },
                        new
                        {
                            BrandId = 65,
                            Name = "Feiyue"
                        },
                        new
                        {
                            BrandId = 66,
                            Name = "Fila"
                        },
                        new
                        {
                            BrandId = 67,
                            Name = "John Fluevog"
                        },
                        new
                        {
                            BrandId = 68,
                            Name = "Foot Locker"
                        },
                        new
                        {
                            BrandId = 69,
                            Name = "Foreva"
                        },
                        new
                        {
                            BrandId = 70,
                            Name = "Geox"
                        },
                        new
                        {
                            BrandId = 71,
                            Name = "Givova"
                        },
                        new
                        {
                            BrandId = 72,
                            Name = "Globe International"
                        },
                        new
                        {
                            BrandId = 73,
                            Name = "Golden Goose (company)"
                        },
                        new
                        {
                            BrandId = 74,
                            Name = "Goldstar shoes"
                        },
                        new
                        {
                            BrandId = 75,
                            Name = "Goodwill Shoe Company"
                        },
                        new
                        {
                            BrandId = 76,
                            Name = "Grand Sport Group"
                        },
                        new
                        {
                            BrandId = 77,
                            Name = "Gravati"
                        },
                        new
                        {
                            BrandId = 78,
                            Name = "Grendene"
                        },
                        new
                        {
                            BrandId = 79,
                            Name = "Hanes Australasia"
                        },
                        new
                        {
                            BrandId = 80,
                            Name = "Hanwag"
                        },
                        new
                        {
                            BrandId = 81,
                            Name = "Havaianas"
                        },
                        new
                        {
                            BrandId = 82,
                            Name = "Heelys"
                        },
                        new
                        {
                            BrandId = 83,
                            Name = "Herbert Levine (company)"
                        },
                        new
                        {
                            BrandId = 84,
                            Name = "Hi-Tec"
                        },
                        new
                        {
                            BrandId = 85,
                            Name = "Hoka One One"
                        },
                        new
                        {
                            BrandId = 86,
                            Name = "Humanic"
                        },
                        new
                        {
                            BrandId = 87,
                            Name = "The Hundreds"
                        },
                        new
                        {
                            BrandId = 88,
                            Name = "Hunter Boot Ltd"
                        },
                        new
                        {
                            BrandId = 89,
                            Name = "Hush Puppies"
                        },
                        new
                        {
                            BrandId = 90,
                            Name = "Inch2"
                        },
                        new
                        {
                            BrandId = 91,
                            Name = "Insolia"
                        },
                        new
                        {
                            BrandId = 92,
                            Name = "Invicta (company)"
                        },
                        new
                        {
                            BrandId = 93,
                            Name = "IPath Footwear"
                        },
                        new
                        {
                            BrandId = 94,
                            Name = "Irregular Choice"
                        },
                        new
                        {
                            BrandId = 95,
                            Name = "Jello Shoecompany"
                        },
                        new
                        {
                            BrandId = 96,
                            Name = "Jogarbola"
                        },
                        new
                        {
                            BrandId = 97,
                            Name = "Johnston & Murphy"
                        },
                        new
                        {
                            BrandId = 98,
                            Name = "Joma"
                        },
                        new
                        {
                            BrandId = 99,
                            Name = "Journeys (company)"
                        },
                        new
                        {
                            BrandId = 100,
                            Name = "K-Swiss"
                        },
                        new
                        {
                            BrandId = 101,
                            Name = "KangaRoos"
                        },
                        new
                        {
                            BrandId = 102,
                            Name = "Kappa (brand)"
                        },
                        new
                        {
                            BrandId = 103,
                            Name = "Keds"
                        },
                        new
                        {
                            BrandId = 104,
                            Name = "Kickers (brand)"
                        },
                        new
                        {
                            BrandId = 105,
                            Name = "Kinney Shoes"
                        },
                        new
                        {
                            BrandId = 106,
                            Name = "Koyo Bear"
                        },
                        new
                        {
                            BrandId = 107,
                            Name = "Kubba Sportswear"
                        },
                        new
                        {
                            BrandId = 108,
                            Name = "Kustom (footwear)"
                        },
                        new
                        {
                            BrandId = 109,
                            Name = "La New"
                        },
                        new
                        {
                            BrandId = 110,
                            Name = "La Sportiva"
                        },
                        new
                        {
                            BrandId = 111,
                            Name = "Leder und Schuh"
                        },
                        new
                        {
                            BrandId = 112,
                            Name = "Legea"
                        },
                        new
                        {
                            BrandId = 113,
                            Name = "Li-Ning"
                        },
                        new
                        {
                            BrandId = 114,
                            Name = "Loake"
                        },
                        new
                        {
                            BrandId = 115,
                            Name = "John Lobb Bootmaker"
                        },
                        new
                        {
                            BrandId = 116,
                            Name = "Lotto Sport Italia"
                        },
                        new
                        {
                            BrandId = 117,
                            Name = "Lugz"
                        },
                        new
                        {
                            BrandId = 118,
                            Name = "Luigi Voltan"
                        },
                        new
                        {
                            BrandId = 119,
                            Name = "Steve Madden, Ltd."
                        },
                        new
                        {
                            BrandId = 120,
                            Name = "Melville Shoe Corporation"
                        },
                        new
                        {
                            BrandId = 121,
                            Name = "Merrell (company)"
                        },
                        new
                        {
                            BrandId = 122,
                            Name = "Mills (sports brand)"
                        },
                        new
                        {
                            BrandId = 123,
                            Name = "Moon Boot"
                        },
                        new
                        {
                            BrandId = 124,
                            Name = "Muji"
                        },
                        new
                        {
                            BrandId = 125,
                            Name = "Munich (sport shoes)"
                        },
                        new
                        {
                            BrandId = 126,
                            Name = "Naot"
                        },
                        new
                        {
                            BrandId = 127,
                            Name = "New Balance"
                        },
                        new
                        {
                            BrandId = 128,
                            Name = "Nike, Inc."
                        },
                        new
                        {
                            BrandId = 129,
                            Name = "Nocona Boots"
                        },
                        new
                        {
                            BrandId = 130,
                            Name = "Vanessa Noel"
                        },
                        new
                        {
                            BrandId = 131,
                            Name = "Northwave"
                        },
                        new
                        {
                            BrandId = 132,
                            Name = "The Original Car Shoe"
                        },
                        new
                        {
                            BrandId = 133,
                            Name = "Original Penguin"
                        },
                        new
                        {
                            BrandId = 134,
                            Name = "Ortuseight"
                        },
                        new
                        {
                            BrandId = 135,
                            Name = "Osiris Shoes"
                        },
                        new
                        {
                            BrandId = 136,
                            Name = "Panam (brand)"
                        },
                        new
                        {
                            BrandId = 137,
                            Name = "Pearl Izumi"
                        },
                        new
                        {
                            BrandId = 138,
                            Name = "Pediped Footwear"
                        },
                        new
                        {
                            BrandId = 139,
                            Name = "PF Flyers"
                        },
                        new
                        {
                            BrandId = 140,
                            Name = "R. M. Williams (company)"
                        },
                        new
                        {
                            BrandId = 141,
                            Name = "Real United"
                        },
                        new
                        {
                            BrandId = 142,
                            Name = "Red or Dead"
                        },
                        new
                        {
                            BrandId = 143,
                            Name = "Reebok Ventilator"
                        },
                        new
                        {
                            BrandId = 144,
                            Name = "Reef (company)"
                        },
                        new
                        {
                            BrandId = 145,
                            Name = "Rockport (company)"
                        },
                        new
                        {
                            BrandId = 146,
                            Name = "Template:Running shoe brands"
                        },
                        new
                        {
                            BrandId = 147,
                            Name = "Russell & Bromley"
                        },
                        new
                        {
                            BrandId = 148,
                            Name = "Samuel Hubbard Shoe Company"
                        },
                        new
                        {
                            BrandId = 149,
                            Name = "Sanders & Sanders Ltd."
                        },
                        new
                        {
                            BrandId = 150,
                            Name = "SAS (shoemakers)"
                        },
                        new
                        {
                            BrandId = 151,
                            Name = "Sebago (company)"
                        },
                        new
                        {
                            BrandId = 152,
                            Name = "Sergio Rossi"
                        },
                        new
                        {
                            BrandId = 153,
                            Name = "Sessions (clothing company)"
                        },
                        new
                        {
                            BrandId = 154,
                            Name = "Daniella Shevel"
                        },
                        new
                        {
                            BrandId = 155,
                            Name = "ShoeDazzle"
                        },
                        new
                        {
                            BrandId = 156,
                            Name = "Shy (company)"
                        },
                        new
                        {
                            BrandId = 157,
                            Name = "Sidi (company)"
                        },
                        new
                        {
                            BrandId = 158,
                            Name = "Simod"
                        },
                        new
                        {
                            BrandId = 159,
                            Name = "Skechers"
                        },
                        new
                        {
                            BrandId = 160,
                            Name = "SLAM (clothing)"
                        },
                        new
                        {
                            BrandId = 161,
                            Name = "Paul Smith (fashion designer)"
                        },
                        new
                        {
                            BrandId = 162,
                            Name = "Solovair"
                        },
                        new
                        {
                            BrandId = 163,
                            Name = "Sorel (brand)"
                        },
                        new
                        {
                            BrandId = 164,
                            Name = "Source Vagabond Systems"
                        },
                        new
                        {
                            BrandId = 165,
                            Name = "Source Sandals"
                        },
                        new
                        {
                            BrandId = 166,
                            Name = "Start-rite"
                        },
                        new
                        {
                            BrandId = 167,
                            Name = "Superga (brand)"
                        },
                        new
                        {
                            BrandId = 168,
                            Name = "Tecovas (company)"
                        },
                        new
                        {
                            BrandId = 169,
                            Name = "Thom McAn"
                        },
                        new
                        {
                            BrandId = 170,
                            Name = "Tod's"
                        },
                        new
                        {
                            BrandId = 171,
                            Name = "Tom Ford (brand)"
                        },
                        new
                        {
                            BrandId = 172,
                            Name = "Toms Shoes"
                        },
                        new
                        {
                            BrandId = 173,
                            Name = "Tredair"
                        },
                        new
                        {
                            BrandId = 174,
                            Name = "Tricker's"
                        },
                        new
                        {
                            BrandId = 175,
                            Name = "Troentorp Clogs"
                        },
                        new
                        {
                            BrandId = 176,
                            Name = "UGG (brand)"
                        },
                        new
                        {
                            BrandId = 177,
                            Name = "Unification Shoes"
                        },
                        new
                        {
                            BrandId = 178,
                            Name = "United Nude"
                        },
                        new
                        {
                            BrandId = 179,
                            Name = "Vans"
                        },
                        new
                        {
                            BrandId = 180,
                            Name = "Veja (brand)"
                        },
                        new
                        {
                            BrandId = 181,
                            Name = "Veldskoen Shoes"
                        },
                        new
                        {
                            BrandId = 182,
                            Name = "Veritas Bespoke"
                        },
                        new
                        {
                            BrandId = 183,
                            Name = "Vibram"
                        },
                        new
                        {
                            BrandId = 184,
                            Name = "Volley (shoe)"
                        },
                        new
                        {
                            BrandId = 185,
                            Name = "Walk-Over shoes"
                        },
                        new
                        {
                            BrandId = 186,
                            Name = "Warrix Sports"
                        },
                        new
                        {
                            BrandId = 187,
                            Name = "Stuart Weitzman"
                        },
                        new
                        {
                            BrandId = 188,
                            Name = "J. M. Weston"
                        },
                        new
                        {
                            BrandId = 189,
                            Name = "Wildsmith Shoes"
                        },
                        new
                        {
                            BrandId = 190,
                            Name = "World Balance"
                        },
                        new
                        {
                            BrandId = 191,
                            Name = "Xtep"
                        },
                        new
                        {
                            BrandId = 192,
                            Name = "Yohji Yamamoto"
                        },
                        new
                        {
                            BrandId = 193,
                            Name = "Yull Shoes"
                        },
                        new
                        {
                            BrandId = 194,
                            Name = "Giuseppe Zanotti"
                        });
                });

            modelBuilder.Entity("SneakerServer.Models.Sneaker", b =>
                {
                    b.Property<int>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Collaboration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorWay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RetailPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SneakerId")
                        .HasName("PrimaryKey_SneakerId");

                    b.HasIndex("Model");

                    b.ToTable("Sneakers");
                });

            modelBuilder.Entity("SneakerServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e376b4e-d236-45dc-ad3d-c59595b228e5"),
                            AccessFailedCount = 0,
                            Birthday = new DateTime(1989, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "1b06e71a-5120-4dd9-951b-9e115076e6c9",
                            Email = "alex4zanetti@hotmail.it",
                            EmailConfirmed = true,
                            LastName = "Orvieto",
                            LockoutEnabled = false,
                            Name = "Alessio",
                            NormalizedEmail = "ALEX4ZANETTI@HOTMAIL.IT",
                            PhoneNumber = "3458048190",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Laniere"
                        },
                        new
                        {
                            Id = new Guid("6630f933-d653-446b-915d-d2ee7c93894a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ade2e5c-4a6a-4ce8-84d7-03c6fffd2fc0",
                            Email = "pippo@hotmail.it",
                            EmailConfirmed = false,
                            LastName = "Franco",
                            LockoutEnabled = false,
                            Name = "Pippo",
                            NormalizedEmail = "PIPPO@HOTMAIL.IT",
                            PhoneNumber = "3458048190",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "PippoFranco"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SneakerServer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SneakerServer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SneakerServer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SneakerServer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SneakerServer.Models.Sneaker", b =>
                {
                    b.HasOne("SneakerServer.Models.Brand", "Brand")
                        .WithMany("Sneakers")
                        .HasForeignKey("SneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SneakerServer.Models.User", b =>
                {
                    b.OwnsOne("SneakerServer.Models.StreetAddress", "StreetAddress", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("StreetAddress");
                });

            modelBuilder.Entity("SneakerServer.Models.Brand", b =>
                {
                    b.Navigation("Sneakers");
                });
#pragma warning restore 612, 618
        }
    }
}
