using Microsoft.AspNetCore.Mvc;

namespace SneakerServer.Controllers;

[ApiController]
[Route("[controller]")]
public class UserController : ControllerBase //controller add ViewBag and ViewResult. not necessary for pure asp.net core WebAPI
{
  private readonly SneakerContext _context;
  private readonly ILogger<UserController> _logger;

  public UserController(ILogger<UserController> logger, SneakerContext context)
  {
    _logger = logger;
    _context = context;
  }

  [HttpGet("{id}")]
  [ProducesResponseType(200)] // This attribute produces more descriptive response details for web API help pages generated by tools like Swagger
  [ProducesResponseType(404)]
  public ActionResult<User> Get(int id)
  {
    User? user = _context.Users.Find(id);
    return user == null ? NotFound() : Ok(user);
  }

}