namespace SneakerServer.Controllers;

[ApiController]
[Route("[controller]")]
[Authorize]
public class UserController(ILogger<UserController> logger, SneakerContext context) : ControllerBase //controller add ViewBag and ViewResult. not necessary for pure asp.net core WebAPI
{
  private readonly ILogger<UserController> _logger = logger;
  private readonly GenericRepository<User> _repository = new(context);

  [HttpGet("{id}")]
  [ProducesResponseType(200)] // This attribute produces more descriptive response details for web API help pages generated by tools like Swagger
  [ProducesResponseType(404)]
  public IActionResult Get(int id)
  {
    User? user = _repository.GetById(id);
    return user == null ? NotFound() : Ok(user);
  }

  // Framework design guidelines recommend using the class Collection when you need to return a collection that is modifiable by the caller or ReadOnlyCollection for read only collections
  [HttpGet()]
  [ProducesResponseType(200)]
  public IActionResult GetAll()
  {
    IEnumerable<User> users = _repository.GetAll();
    return Ok(users);
  }

  [HttpPost()]
  [ProducesResponseType(200)]
  public IActionResult Insert(User user)
  {
    _repository.Insert(user);
    _repository.Save();
    return Ok(user);
  }

  [HttpPatch()]
  [ProducesResponseType(200)]
  [ProducesResponseType(400)]
  public IActionResult Update(User user)
  {
    _repository.Update(user);
    _repository.Save();
    return Ok(user);
  }

  [HttpDelete()]
  [ProducesResponseType(200)]
  [ProducesResponseType(400)]
  public IActionResult Delete(int id)
  {
    _repository.Delete(id);
    _repository.Save();
    return Ok();
  }
}